language: erlang
before_install:
  - sudo apt-get install libpam0g-dev
before_install:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
  - sudo mv rebar3 /usr/bin
  - sudo echo "#!/usr/bin/env bash" > `which rebar`
script:
  - make check
otp_release:
  - 18.2
  - 17.5
  - R16B03-1
  - R15B03
